### PR TITLE
Added logging to output so we can see timings

### PR DESCRIPTION
**Pull request by oblodgett**
I am by no means a python-dev, but we need to do something.

### CODE REVIEW

**Comment by christabone** [comment]
There's a more efficient way to carry the logger settings across Python modules, I can tweak the code tomorrow morning.

**Comment by oblodgett** [comment]
Great thanks... I was thinking it would be better if there was one and we carry it forward to all. Or if there was a way to sorta override the "print" method so it could go through a logger.

**Comment by christabone** [comment]
The config doesn't need to be called at the top of each file, only the `import` and 

`logger = logging.getLogger(__name__)`

**Comment by christabone** [comment]
Also, the level of logging you specified is printing out every single Neo4j transaction, as far as I can tell.

**Comment by christabone** [comment]
@oblodgett Do you need to manually set the level to DEBUG on all those pages? I think you can set the default in the aggregate file and then override it only if necessary...?

**Pull request merged**
