### PR TITLE
AGR-2375

### PR DESCRIPTION
**Pull request by ianlongden**
Two fixes.

Docker build now works (added gcc and removed pprint form requirements).

Can now specify a different branch to obtain agr_schema files from. NOTE: this should only be used for testing really.

### CODE REVIEW

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6020161&bid=19733512)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6020161&bid=19733512)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6020161&bid=19733512)

**Comment by ianlongden** [comment]
How long does the LoaderPR/BuildAndTest take its been over an hour? Can it get stuck?

**Comment by sierra-moxon** [comment]
a couple of builds are going - my PR is running there too - I imagine it'll be awhile.

**Comment by ianlongden** [comment]
Okay Thanks, I was just worried it had got stuck in some loop or something. I shall 'try' and be more patient.

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6020161&bid=19733512)

**Pull request merged**
