### PR TITLE
Genedesc 3.1

### PR DESCRIPTION
**Pull request by valearna**
- Added standard headers to txt and tsv download files
- Modified descriptions following reviewers' comments from DATABASE paper
- New gene description software version in requirements

### CODE REVIEW

**Comment by valearna** [comment]
Thanks for the comment @azurebrd

> Cool to see how you're handling the header template. Are we supposed to use 6fea7c7a12ef8f53de17f31f8a8bd3b468cb41e7 ? I thought we were supposed to use https://raw.githubusercontent.com/alliance-genome/agr_file_generator/master/src/generators/header_template.txt Thanks.

Yes, you are right - It's better to use the version in the master branch. I'll fix that.

**Comment by oblodgett** [comment]
Is there any other way we can do this vs using a hardcoded URL?
HEADER_TEMPLATE_URL

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 3
           

Clones added
============
- src/etl/gene_descriptions_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=5603718&bid=18356368)

**Comment by valearna** [comment]
> Is there any other way we can do this vs using a hardcoded URL?
> HEADER_TEMPLATE_URL

What about an env variable? We can set the default value in `default_env_vars.yml` in the loader code

**Comment by oblodgett** [comment]
What happens when the code goes to stage and then there is a change that needs to happen to the header file... it will be made in the release branch not master. Or a change is made in master for the next release while we are still on the current release.

**Comment by oblodgett** [comment]
I thought the solution for this was going to be a separate repo for these headers?

**Comment by valearna** [comment]
We decided to use the header template from `agr_file_generator` that Paulo set up, but @adamjohnwright also suggested that the repo could become a pip package in the future so that we can directly import a function to generate the headers. For now I would continue to pull the header template from github, maybe specifying a release version or a specific commit.

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 3
           

Clones added
============
- src/etl/gene_descriptions_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=5603718&bid=18356368)

**Pull request merged**
