### PR TITLE
prevent creating crossreferences when the object connected to is a -

### PR DESCRIPTION
**Pull request by azurebrd**

### CODE REVIEW

**Comment by azurebrd** [comment]
This is NOT ready to merge.

**Comment by azurebrd** [comment]
@oblodgett Just checking in with you about this PR/Run not working.  gocd says : 
[go] Task: /bin/bash -c "docker run --rm --mount type=bind,source=/home/core/.password,target=/usr/src/ansible/.password -e PLAYBOOK_NAME=${GO_PIPELINE_NAME} -e ALLIANCE_RELEASE=${ALLIANCE_RELEASE} ${REG}/agr_ansible_run:${ALLIANCE_RELEASE} ansible-playbook -e env=$NET -i hosts playbook_run_loader_integration_tests.yml --vault-password-file=.password"took: 48m 19.370sexited: 2

**Comment by azurebrd** [comment]
Chris Grove's signed off on making the changes.  Once the required failure is fixed, this can be merged.

**Comment by christabone** [comment]
@azurebrd It's actually a loader test failing. This is from the logs:
```

an 28 23:20:24 agr.testing.loader.test pytest --verbose: =================================== FAILURES ===================================
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: _________________ test_expression_for_non_human_species_exists _________________
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:         """
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:         Test Expression for Non Human Species Exists
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:     def test_expression_for_non_human_species_exists():
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:         Not used for SARS-CoV-2.
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:         """
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:                  RETURN count(distinct s) AS counter"""
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:         query = """MATCH (s:Species)--(:Gene)-[hp:EXPRESSED_IN]-(e:ExpressionBioEntity)
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:         result = execute_transaction(query)
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:     
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: E             -6
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: src/test/specific_tests.py:357: AssertionError
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: >           assert record["counter"] == 6
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: E             +5
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:         for record in result:
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: E           assert 5 == 6
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:   /usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.2) or chardet (3.0.4) doesn't match a supported version!
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: =============================== warnings summary ===============================
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose:     RequestsDependencyWarning)
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: ../../lib/python3/dist-packages/requests/__init__.py:80
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: -- Docs: https://docs.pytest.org/en/stable/warnings.html
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: =========================== short test summary info ============================
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: FAILED src/test/specific_tests.py::test_expression_for_non_human_species_exists
Jan 28 23:20:24 agr.testing.loader.test pytest --verbose: ================== 1 failed, 512 passed, 1 warning in 53.38s ===================
```

**Comment by azurebrd** [comment]
Oh, thanks @christabone .  Where can I see the logs ?  From the PR I see a link to https://gocd.alliancegenome.org/go/tab/build/detail/LoaderPR/676/Run/1/RunContainer and see failures in the console and Failures tabs, but don't see where the logs are.  Are they linked from somewhere in there ?

**Comment by christabone** [comment]
@azurebrd We have them over in Kibana here: https://kibana.alliancegenome.org/app/logtrail#/?q=*&h=agr.testing.loader.test&t=Now&i=logstash-*&_g=()

Does that link work for you? If not, we can get you access.

**Comment by azurebrd** [comment]
Ah, gotcha, thanks @christabone .  If there's a failure just always check kibana.  Yes, I can access it.  Thanks !

**Comment by azurebrd** [comment]
Hey @christabone , this LoaderPR/Run failed because of the unrelated data issues.  @chris-grove tells me that a separate loader build finished.  Do you know if I can kick off running this again in this ticket through the github webpage, or should I just make a tiny commit that doesn't do anything and push it here to re-trigger it ?

**Comment by christabone** [comment]
@azurebrd It looks like it's out of date with the base [master] branch, so you could always try the "Update branch" button and that should kick off the tests again.

**Comment by azurebrd** [comment]
Thanks @christabone !

**Review by christabone — APPROVED** [review]

**Comment by christabone** [comment]
@azurebrd It looked like AWS killed our spot instance during the loader test. I restarted it and it looks good. We'll have to see how often AWS stops our spot instances and whether it makes sense to use dedicated ones instead.

**Comment by azurebrd** [comment]
Thanks @christabone !

**Pull request merged**
