### PR TITLE
fix unit tests AGR-1622 AGR-2423 AGR-2424

### PR DESCRIPTION
**Pull request by sierra-moxon**

### CODE REVIEW

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- src/etl/htp_metadataset_etl.py  2
- src/etl/vep_transcript_etl.py  1
- src/etl/bgi_etl.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6234817&bid=20315846)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- src/etl/bgi_etl.py  1
- src/etl/htp_metadataset_etl.py  2
- src/etl/vep_transcript_etl.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6234817&bid=20315846)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- src/etl/vep_transcript_etl.py  1
- src/etl/htp_metadataset_etl.py  2
- src/etl/bgi_etl.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6234817&bid=20315846)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- src/etl/htp_metadataset_etl.py  2
- src/etl/bgi_etl.py  1
- src/etl/vep_transcript_etl.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6234817&bid=20315846)

**Review by azurebrd — COMMENTED** [review]
At src/etl/ecomap_etl.py line 111, it looks like you may have left out a new eco entry, or alternatively need to remove the extra append in line 112.

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- src/etl/vep_transcript_etl.py  1
- src/etl/bgi_etl.py  1
- src/etl/htp_metadataset_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6234817&bid=20315846)

**Review by azurebrd — APPROVED** [review]

**Pull request merged**
