### PR TITLE
Avoid issues with duplicate transcript names across MODs

### PR DESCRIPTION
**Pull request by markquintontulloch**
Make sure curie (which becomes primaryKey) is unique and ensure CDS linked to correct Transcript by searching for both gff3ID and dataProvider fields.

### CODE REVIEW

**Comment by christabone** [comment]
I wonder if this might cause issues with Xenbase data if the two different species share transcript names but the same data provider?

**Comment by christabone** [comment]
I can check on Monday.

**Comment by christabone** [comment]
Also, we might need to change other transcript MATCH commands in additional ETL scripts?

**Comment by markquintontulloch** [comment]
Data provider for Xenbase would be XBXL and XBXT

**Comment by christabone** [comment]
Awesome, that's good to know. Thanks for figuring this out, this is great.

**Comment by markquintontulloch** [comment]
Hmm, we’ll possibly need to change the match on the vep_transcript.etl.  I’ll have to take a look at the VEP output.

**Comment by christabone** [comment]
The protein sequence ETL might need updating as well, that's one of the places it was failing earlier and I _think_ it might have a Transcript MATCH command.

**Comment by markquintontulloch** [comment]
The protein ETL should be good. It does a query based on association with other entities to pulls out the Transcript primary key, which it then uses in the query to associate the protein with the transcript.  The VEP one is tricky though as I don’t think the dataProvider is readily accessible to use in the query - I think I’ll need to make some changes to the VEP pipeline too and regenerate the VEP files.

**Comment by markquintontulloch** [comment]
@christabone - I've checked through again and I don't think any of the other ETLs need to be updated.  However, what I did find is that there is overlap between the curies used for transcripts in the XBXL and XBXT files.  They both used the format `modelID:rna12345` and there are about ~2.5k that appear in both files.  As such I have changed the curies to be in the format `XBXL:rna12345` and `XBXT:rna12345` and have reuploaded them, so we'll need to take a new snapshot.  Xenbase may wish to chose different curie prefixes, which is fine (it doesn't have to match the data provider name) so long as there is no overlap between the two species.

There is also more work to be done on the XB GFFs as we required `transcript_id`, `gene_id`, and `protein_id` attributes in column 9 on the appropriate rows of the GFF - I think there's some details somewhere in the DQM minutes/documents, but probably easier to just look at other MODs for examples.  However, I don't think any of this is urgent given the files currently submitted by XB and shouldn't affect the loading of those files.

**Comment by christabone** [comment]
@markquintontulloch Do we want to merge this separately from the VEP work you think might need to happen?

**Comment by markquintontulloch** [comment]
Having looked at it, there is no VEP work required

**Comment by markquintontulloch** [comment]
@christabone - The VEP transcript ETL uses 'curie' for matching Transcripts, which is unaffected by the changes here as 'curie' is specified as an attribute in the GFFs and was already distinct between RGD and XB.  It wasn't distinct between XBXL and XBXT, which is why I updated the curies in the GFFs.  So, I think we're good to merge?

**Comment by christabone** [comment]
Sounds great, let's do it.

**Review by christabone — APPROVED** [review]

**Pull request merged**
