### PR TITLE
Transcript   AGR-1885

### PR DESCRIPTION
**Pull request by sierra-moxon**

### CODE REVIEW

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- src/etl/veptranscript.py  9
- src/etl/allele_etl.py  1
- src/etl/transcript_etl.py  3
         

Clones added
============
- src/etl/veptranscript.py  7
- src/etl/vep_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=4996387&bid=16490054)

**Comment by christabone** [comment]
@sierra-moxon I think there are two small conflicts due to the molecular interaction rename.

**Comment by sierra-moxon** [comment]
yeah don't worry about this one yet - thanks for checking, I'm still testing on it.

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 7
           

Complexity increasing per file
==============================
- src/etl/veptranscript.py  9
- src/etl/allele_etl.py  1
- src/etl/transcript_etl.py  3
         

Clones added
============
- src/etl/vep_etl.py  2
- src/etl/veptranscript.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=4996387&bid=16490054)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- src/etl/veptranscript.py  9
- src/etl/allele_etl.py  1
- src/etl/transcript_etl.py  3
         

Clones added
============
- src/etl/veptranscript.py  7
- src/etl/vep_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=4996387&bid=16490054)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- src/etl/transcript_etl.py  3
- src/etl/veptranscript.py  9
- src/etl/allele_etl.py  1
         

Clones added
============
- src/etl/veptranscript.py  7
- src/etl/vep_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=4996387&bid=16490054)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- src/etl/veptranscript.py  9
- src/etl/transcript_etl.py  3
- src/etl/allele_etl.py  1
         

Clones added
============
- src/etl/veptranscript.py  7
- src/etl/vep_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=4996387&bid=16490054)

**Pull request merged**
