### PR TITLE
First implementation of HTP dataset/sample load

### PR DESCRIPTION
**Pull request by sierra-moxon**

### CODE REVIEW

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 24
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  52
- src/etl/htp_metadataset_etl.py  24
         

Clones added
============
- src/etl/htp_metadatasample_etl.py  8
- src/etl/htp_metadataset_etl.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 21
           

Complexity increasing per file
==============================
- src/etl/htp_metadataset_etl.py  24
- src/etl/htp_metadatasample_etl.py  52
         

Clones added
============
- src/etl/htp_metadataset_etl.py  4
- src/etl/htp_metadatasample_etl.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 20
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  52
- src/etl/htp_metadataset_etl.py  24
         

Clones added
============
- src/etl/htp_metadatasample_etl.py  8
- src/etl/htp_metadataset_etl.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 20
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  52
- src/etl/htp_metadataset_etl.py  24
         

Clones added
============
- src/etl/htp_metadatasample_etl.py  8
- src/etl/htp_metadataset_etl.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 20
           

Complexity increasing per file
==============================
- src/etl/htp_metadataset_etl.py  24
- src/etl/htp_metadatasample_etl.py  52
         

Clones added
============
- src/etl/htp_metadataset_etl.py  4
- src/etl/htp_metadatasample_etl.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 20
           

Complexity increasing per file
==============================
- src/etl/htp_metadataset_etl.py  24
- src/etl/htp_metadatasample_etl.py  52
         

Clones added
============
- src/etl/htp_metadataset_etl.py  4
- src/etl/htp_metadatasample_etl.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 20
           

Complexity increasing per file
==============================
- src/etl/htp_metadataset_etl.py  24
- src/etl/htp_metadatasample_etl.py  52
         

Clones added
============
- src/etl/htp_metadataset_etl.py  4
- src/etl/htp_metadatasample_etl.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 22
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  52
         

Clones added
============
- src/etl/htp_metadataset_etl.py  4
- src/etl/htp_metadatasample_etl.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 21
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  52
- src/etl/htp_metadataset_etl.py  27
         

Clones added
============
- src/etl/htp_metadatasample_etl.py  8
- src/etl/htp_metadataset_etl.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 21
           

Complexity increasing per file
==============================
- src/etl/htp_metadataset_etl.py  27
- src/etl/htp_metadatasample_etl.py  52
         

Clones added
============
- src/etl/htp_metadataset_etl.py  4
- src/etl/htp_metadatasample_etl.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
@sierra-moxon Do we want to bring this in or @ianlongden's changes first?

**Comment by sierra-moxon** [comment]
@christabone - just a clarification, wasn't this one opened earlier?

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 23
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  52
- src/etl/htp_metadataset_etl.py  27
         

Clones added
============
- src/etl/htp_metadatasample_etl.py  7
- src/etl/htp_metadataset_etl.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 21
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  52
- src/etl/htp_metadataset_etl.py  27
         

Clones added
============
- src/etl/htp_metadatasample_etl.py  7
- src/etl/htp_metadataset_etl.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 27
           

Complexity increasing per file
==============================
- src/etl/htp_metadataset_etl.py  25
- src/etl/htp_metadatasample_etl.py  50
         

Clones added
============
- src/etl/htp_metadataset_etl.py  2
- src/etl/htp_metadatasample_etl.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 27
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  50
- src/etl/htp_metadataset_etl.py  25
         

Clones added
============
- src/etl/htp_metadatasample_etl.py  8
- src/etl/htp_metadataset_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 27
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  52
- src/etl/htp_metadataset_etl.py  25
         

Clones added
============
- src/etl/htp_metadatasample_etl.py  6
- src/etl/htp_metadataset_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 27
           

Complexity increasing per file
==============================
- src/etl/htp_metadataset_etl.py  25
- src/etl/htp_metadatasample_etl.py  52
         

Complexity decreasing per file
==============================
+ src/etl/vep_etl.py  -1
         

Clones added
============
- src/etl/htp_metadataset_etl.py  2
- src/etl/htp_metadatasample_etl.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6027992&bid=19755937)

**Pull request merged**
