### PR TITLE
add calculated crossRefUrl for this release for search

### PR DESCRIPTION
**Pull request by sierra-moxon**
- fix FB and MGI exon-transcript-variant relations post GFF3 1.0.1.3 submission changes.

### CODE REVIEW

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity decreasing per file
==============================
+ src/etl/transcript_etl.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6185057&bid=20185638)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  1
         

Complexity decreasing per file
==============================
+ src/etl/transcript_etl.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6185057&bid=20185638)

**Review by adamjohnwright — APPROVED** [review]

**Review by azurebrd — APPROVED** [review]

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 1
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  1
         

Complexity decreasing per file
==============================
+ src/etl/transcript_etl.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6185057&bid=20185638)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 1
           

Complexity increasing per file
==============================
- src/etl/htp_metadatasample_etl.py  1
         

Complexity decreasing per file
==============================
+ src/etl/transcript_etl.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6185057&bid=20185638)

**Pull request merged**
