### PR TITLE
fix(disease_via_ortho): using undirected relationship to read ortho data for disease via ortho

### PR DESCRIPTION
**Pull request by valearna**
- directed relationships were used (possibly?) to speed up the disease via ortho query
- using undirected [ORTHOLOGOUS] relationships between genes returns exactly the same results for "old" MODs and adds unidirectional data from XBXL and XBXT orthology that was missing when using directed relationships

### CODE REVIEW

**Comment by christabone** [comment]
@valearna Was it a huge slowdown when it was changed? 

I've also started looking at Neo4j version 4 and using composite indices to speed up the build. :crossed_fingers:

**Review by christabone — APPROVED** [review]

**Comment by valearna** [comment]
@christabone not really. The queries are fast in both cases

**Review by sierra-moxon — APPROVED** [review]

**Comment by valearna** [comment]
it seems that the LoaderPR build is stuck. @oblodgett can you start it manually?

**Comment by christabone** [comment]
@valearna I just re-triggered it.

**Pull request merged**
