### PR TITLE
AGR-754, and fix URLs for RGD link backs

### PR DESCRIPTION
**Pull request by sierra-moxon**
fixing RGD links

### CODE REVIEW

**Comment by sierra-moxon** [comment]
@christabone - if you wouldn't mind, in particular, making sure I have the branches correctly merging for this AGR-754 (RGD link back fix) PR that would be great.  It should be- branch off master requesting to be merged into master. thanks! :)

**Comment by oblodgett** [comment]
This looks good... however when do you want to push this out? We are having a discussion in the UI meeting about when to push a UI fix and its looking like Monday sometime?

**Comment by sierra-moxon** [comment]
I think its good to push all together if possible?

**Comment by oblodgett** [comment]
Yes... that is what I am advocating for so that we don't have to push to www twice... so it looks like it will go Monday morning.

**Pull request merged**
