### PR TITLE
Wt expression AGR-1152 AGR-1011 AGR-1142 AGR-1143 

### PR DESCRIPTION
**Pull request by sierra-moxon**
Major component of this PR is a first pass at WT expression loader with tests, etc...
There are 15 new ontologies being parsed with the old obo parser in place (so that travis memory footprint was under 3G -- happy to remove this once ontobio can be used or we go to a gocd build approach).
Implemented ijson in order to reduce the memory footprint for travis as well.  (Files over ~ 100MB should probably use this library unless we go to a gocd build approach - but it does slow down the load a bit - I think its worth getting it in now, and attempt to do more to tune in the coming weeks because downstream components need to start seeing the data.  The amount of data also has an impact on the load time - between 300,000 and 700,000 annotations per MOD).
There are several new files stubbed out in the new load_targets directory to help run ontologies as one-offs.  It is just a quick first pass at breaking aggregate_loader into runnable components, I'm sure there are better ways to refine this.
The nullable components of an expression pattern gave me some trouble with cypher.  This is a piece that I will continue to refine when I get the next data load (Friday). 
Still to do: map up Uberon terms for stage, and anatomical structures (GO map up will be done in the API)

### CODE REVIEW

**Comment by sierra-moxon** [comment]
@oblodgett - yes - I have a method like that in aggregate loader (used by those individual files) as a first pass.  my next task is to break that method out of aggregate loader all together, and then put urls and types and files into a configuration file instead of the code itself.

**Comment by oblodgett** [comment]
So I know this might be problematic but could we wait on the "split loader" code to better discuss, and only put in the "wt-expression" code?

**Comment by sierra-moxon** [comment]
Its not being used anywhere in the implementation that currently runs - its just helper code for me to run locally at the moment.  I'd rather not fuss with the PR, but could open another to rip it all out again after this goes in?

**Comment by oblodgett** [comment]
No offense but I have heard this argument before and we still have code hanging around, on the java side of the fence, that needs to be cleaned up. Features vs Calling them Allele's, and the same argument was used "get it in" "change it later", now it just Technical debt. Personally, I would like to see it held off.

**Comment by sierra-moxon** [comment]
so you want me to delete that directory?

**Comment by oblodgett** [comment]
Ya, I would like to explore that stuff in another branch... I think we can work on multithreading the loader, there... oh I guess you did it.

**Pull request merged**
