### PR TITLE
update to 4.0

### PR DESCRIPTION
**Pull request by sierra-moxon**

### CODE REVIEW

**Review by oblodgett — APPROVED** [review]

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
- Added 5
           

Complexity increasing per file
==============================
- src/files/download.py  1
- src/data_manager/data_file_manager.py  5
         

Complexity decreasing per file
==============================
+ src/files/gzip_file.py  -1
+ src/data_manager/data_type_config.py  -1
+ src/files/json_file.py  -7
+ src/data_manager/sub_type_config.py  -7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6393047&bid=20733288)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
- Added 5
           

Complexity increasing per file
==============================
- src/files/download.py  1
- src/data_manager/data_file_manager.py  5
         

Complexity decreasing per file
==============================
+ src/files/gzip_file.py  -1
+ src/data_manager/data_type_config.py  -1
+ src/data_manager/sub_type_config.py  -7
+ src/files/json_file.py  -7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6393047&bid=20733288)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
- Added 5
           

Complexity increasing per file
==============================
- src/files/download.py  1
- src/data_manager/data_file_manager.py  5
         

Complexity decreasing per file
==============================
+ src/files/json_file.py  -7
+ src/files/gzip_file.py  -1
+ src/data_manager/sub_type_config.py  -7
+ src/data_manager/data_type_config.py  -1
         

Clones added
============
- src/etl/molecular_interaction_etl.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6393047&bid=20733288)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 5
           

Complexity increasing per file
==============================
- src/files/download.py  1
- src/data_manager/data_file_manager.py  5
         

Complexity decreasing per file
==============================
+ src/data_manager/sub_type_config.py  -7
+ src/files/gzip_file.py  -1
+ src/files/json_file.py  -7
+ src/data_manager/data_type_config.py  -1
         

Clones added
============
- src/etl/molecular_interaction_etl.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6393047&bid=20733288)

**Pull request merged**
