### PR TITLE
Release 1.7.0

### PR DESCRIPTION
**Pull request by dustine32**
This should declutter the logging a bit.

### CODE REVIEW

**Comment by christabone** [comment]
image

These two should never merge (I'm a big fan of the networking view from GitHub).

**Comment by dustine32** [comment]
Sorry @christabone , just to clarify, so this would result in two new PRs? One for `[new release-1.7.0-derived branch] -> release-1.7.0` and another for `[new develop-derived branch] -> develop`?

**Comment by christabone** [comment]
@dustine32 Correct! That's our general approach for post-release-branch development.

**Comment by dustine32** [comment]
Got it! So before I do that, I realized earlier in my screw-up that I pushed my change directly to branch `release-1.7.0`. To revert that can I just `git reset --hard 2005b09` (the last commit before mine) on `release-1.7.0` branch locally, then force push back to remote `release-1.7.0` branch with `git push -f origin release-1.7.0`?

Again, sorry about the questions on basic git usage! Thanks!

**Comment by christabone** [comment]
@oblodgett Did we forget to protect the release branches? It looks like they're not protected.

@dustine32 Don't worry about the accidental commit directly to the release branch. It won't affect anything. You would just end up re-committing the same changes if you reset and then commit again. In the future, go with the branch-merge strategy and everything will be good. We typically protect the release branches to avoid direct commits but I think it was overlooked this time.

**Comment by christabone** [comment]
@dustine32 , To summarize: if the changes you'd like to push out for 1.7 are already in `release-1.7.0`, you're all set on that branch. 

If you haven't put them into `develop`, go ahead and branch `develop`, make your changes, and merge back to `develop`.

**Comment by dustine32** [comment]
@christabone Rats! Are we just gonna let my commit live in the release branch as-is or is there something we can do to revert it and follow the proper branch-merge route? I'll at least get this going for develop. Thanks!

**Comment by dustine32** [comment]
@christabone Sorry, just saw your last comment. Looks like we agree!

**Pull request closed without merging**
