### PR TITLE
Add protein sequences to transcripts with variants

### PR DESCRIPTION
**Pull request by sierra-moxon**

### CODE REVIEW

**Comment by christabone** [comment]
@sierra-moxon A few conflicts from @ianlongden merge. I went with date-priority since he opened his a day earlier. Sorry for the extra work.

**Comment by sierra-moxon** [comment]
@christabone  - just a clarification, wasn't this one opened earlier?

**Comment by christabone** [comment]
@sierra-moxon Ohhhhh, crap. You are correct, sorry. I went by the top sport where it says "Sierra commented 4 days ago..." thinking it meant you opened it 4 days ago. My bad.

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 13
           

Complexity increasing per file
==============================
- src/etl/protein_sequence_etl.py  8
- src/etl/transcript_etl.py  5
         

Clones added
============
- src/etl/protein_sequence_etl.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6056333&bid=19839807)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 13
           

Complexity increasing per file
==============================
- src/etl/protein_sequence_etl.py  8
- src/etl/transcript_etl.py  5
         

Clones added
============
- src/etl/protein_sequence_etl.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6056333&bid=19839807)

**Pull request closed without merging**
