### PR TITLE
AGR-2319

### PR DESCRIPTION
**Pull request by ianlongden**

### CODE REVIEW

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 70
- Added 77
           

Complexity increasing per file
==============================
- src/test/unit_tests.py  12
         

Complexity decreasing per file
==============================
+ src/etl/phenotype_etl.py  -11
+ src/etl/variation_etl.py  -2
+ src/etl/sequence_targeting_reagent_etl.py  -6
+ src/etl/helpers/etl_helper.py  -9
+ src/etl/bgi_etl.py  -22
+ src/etl/affected_genomic_model_etl.py  -20
+ src/etl/allele_etl.py  -17
+ src/etl/construct_etl.py  -15
+ src/etl/disease_etl.py  -29
         

Clones added
============
- src/etl/phenotype_etl.py  1
- src/etl/vep_transcript_etl.py  1
- src/etl/stub_etl.py  1
- src/etl/transcript_etl.py  1
- src/etl/bgi_etl.py  1
- src/etl/closure_etl.py  1
- src/etl/vep_etl.py  1
- src/etl/disease_etl.py  1
- src/etl/generic_ontology_etl.py  1
         

Clones removed
==============
+ src/etl/variation_etl.py  -1
+ src/etl/sequence_targeting_reagent_etl.py  -1
+ src/etl/affected_genomic_model_etl.py  -3
+ src/etl/do_etl.py  -1
+ src/etl/allele_etl.py  -16
+ src/etl/construct_etl.py  -1
+ src/etl/go_etl.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6048274&bid=19814505)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 72
- Added 79
           

Complexity increasing per file
==============================
- src/test/unit_tests.py  12
         

Complexity decreasing per file
==============================
+ src/etl/sequence_targeting_reagent_etl.py  -6
+ src/etl/variation_etl.py  -2
+ src/etl/affected_genomic_model_etl.py  -20
+ src/etl/construct_etl.py  -15
+ src/etl/allele_etl.py  -17
+ src/etl/bgi_etl.py  -22
+ src/etl/phenotype_etl.py  -11
+ src/etl/helpers/etl_helper.py  -9
+ src/etl/disease_etl.py  -29
         

Clones added
============
- src/etl/vep_etl.py  1
- src/etl/transcript_etl.py  1
- src/etl/bgi_etl.py  1
- src/etl/stub_etl.py  1
- src/etl/phenotype_etl.py  1
- src/etl/vep_transcript_etl.py  1
- src/etl/generic_ontology_etl.py  1
- src/etl/disease_etl.py  1
- src/etl/closure_etl.py  1
         

Clones removed
==============
+ src/etl/sequence_targeting_reagent_etl.py  -1
+ src/etl/variation_etl.py  -1
+ src/etl/affected_genomic_model_etl.py  -3
+ src/etl/construct_etl.py  -1
+ src/etl/allele_etl.py  -14
+ src/etl/do_etl.py  -1
+ src/etl/go_etl.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6048274&bid=19814505)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 72
- Added 79
           

Complexity increasing per file
==============================
- src/test/unit_tests.py  12
         

Complexity decreasing per file
==============================
+ src/etl/bgi_etl.py  -22
+ src/etl/construct_etl.py  -15
+ src/etl/affected_genomic_model_etl.py  -20
+ src/etl/sequence_targeting_reagent_etl.py  -6
+ src/etl/variation_etl.py  -2
+ src/etl/disease_etl.py  -29
+ src/etl/phenotype_etl.py  -11
+ src/etl/helpers/etl_helper.py  -9
+ src/etl/allele_etl.py  -17
         

Clones added
============
- src/etl/bgi_etl.py  1
- src/etl/vep_transcript_etl.py  1
- src/etl/vep_etl.py  1
- src/etl/generic_ontology_etl.py  1
- src/etl/stub_etl.py  1
- src/etl/transcript_etl.py  1
- src/etl/closure_etl.py  1
- src/etl/disease_etl.py  1
- src/etl/phenotype_etl.py  1
         

Clones removed
==============
+ src/etl/do_etl.py  -1
+ src/etl/construct_etl.py  -1
+ src/etl/affected_genomic_model_etl.py  -3
+ src/etl/sequence_targeting_reagent_etl.py  -1
+ src/etl/variation_etl.py  -1
+ src/etl/go_etl.py  -1
+ src/etl/allele_etl.py  -14
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6048274&bid=19814505)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 72
- Added 79
           

Complexity increasing per file
==============================
- src/test/unit_tests.py  12
         

Complexity decreasing per file
==============================
+ src/etl/variation_etl.py  -2
+ src/etl/allele_etl.py  -17
+ src/etl/construct_etl.py  -15
+ src/etl/affected_genomic_model_etl.py  -20
+ src/etl/sequence_targeting_reagent_etl.py  -6
+ src/etl/phenotype_etl.py  -11
+ src/etl/disease_etl.py  -29
+ src/etl/bgi_etl.py  -22
+ src/etl/helpers/etl_helper.py  -9
         

Clones added
============
- src/etl/vep_etl.py  1
- src/etl/closure_etl.py  1
- src/etl/transcript_etl.py  1
- src/etl/vep_transcript_etl.py  1
- src/etl/phenotype_etl.py  1
- src/etl/generic_ontology_etl.py  1
- src/etl/disease_etl.py  1
- src/etl/bgi_etl.py  1
- src/etl/stub_etl.py  1
         

Clones removed
==============
+ src/etl/variation_etl.py  -1
+ src/etl/allele_etl.py  -14
+ src/etl/construct_etl.py  -1
+ src/etl/affected_genomic_model_etl.py  -3
+ src/etl/sequence_targeting_reagent_etl.py  -1
+ src/etl/go_etl.py  -1
+ src/etl/do_etl.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6048274&bid=19814505)

**Comment by ianlongden** [comment]
Too many codacy emails. Will resubmit after final solution is ready.

**Pull request closed without merging**
