### PR TITLE
AGR-2592 fix casing mismatch in mapping

### PR DESCRIPTION
**Pull request by azurebrd**

### CODE REVIEW

**Review by christabone — APPROVED** [review]

**Comment by christabone** [comment]
Testing might fail without @mluypaert 's changes first?

**Comment by azurebrd** [comment]
Oh, thanks @christabone  I thought this had passed a few days ago.  I'd pulled from master, and made changes off a branch there.  If it should wait, that's good. @mluypaert does that sound right ? Thanks.

**Comment by mluypaert** [comment]
> 
> 
> Testing might fail without @mluypaert 's changes first from the other PR?

I still need to merge in that PR (it's approved but intentionally not merged yet), but there are some other GoCD changes ongoing at the moment that would indeed hold up this PR pipeline. Let me check it I can activate it again for now (I'll break it again later, probably tomorrow)

**Comment by azurebrd** [comment]
Thanks @mluypaert .  I think there's no rush to merge this in, is that right @chris-grove ?

**Comment by mluypaert** [comment]
Running now 🤞

**Comment by chris-grove** [comment]
@azurebrd  Well, no huge rush, but I'd like to get it in soon to test before the 4.0 code freeze

**Comment by azurebrd** [comment]
The checks passed, @christabone and @mluypaert , is it okay to merge this ?

**Comment by christabone** [comment]
Yep! Should be good to go. @mluypaert that OK by you?

**Comment by mluypaert** [comment]
> 
> 
> The checks passed, @christabone and @mluypaert , is it okay to merge this ?

Yep, good by me as well

**Comment by azurebrd** [comment]
Great, thanks you all ! @mluypaert @christabone @chris-grove

**Pull request merged**
