### PR TITLE
AGR-2319

### PR DESCRIPTION
**Pull request by ianlongden**

### CODE REVIEW

**Comment by ianlongden** [comment]
So tests okay locally. Not sure about order of PR's but my guess is I will have to bring this back up to date once other PRs have been done as In all likely hood we may have altered the same files. Anyway  I can find time this week to do that once the testing is all working again.

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 74
- Added 75
           

Complexity increasing per file
==============================
- src/test/unit_tests.py  12
         

Complexity decreasing per file
==============================
+ src/etl/variation_etl.py  -2
+ src/etl/helpers/obo_helper.py  -20
+ src/etl/allele_etl.py  -17
+ src/etl/do_etl.py  -7
+ src/etl/affected_genomic_model_etl.py  -20
+ src/etl/sequence_targeting_reagent_etl.py  -6
+ src/etl/construct_etl.py  -15
+ src/etl/bgi_etl.py  -22
+ src/etl/disease_etl.py  -29
+ src/etl/helpers/etl_helper.py  -9
+ src/etl/phenotype_etl.py  -11
         

Clones added
============
- src/etl/transcript_etl.py  1
- src/etl/closure_etl.py  1
- src/etl/vep_transcript_etl.py  1
- src/etl/stub_etl.py  1
- src/etl/vep_etl.py  1
- src/etl/bgi_etl.py  1
- src/etl/generic_ontology_etl.py  1
- src/etl/phenotype_etl.py  1
         

Clones removed
==============
+ src/etl/variation_etl.py  -1
+ src/etl/go_etl.py  -1
+ src/etl/helpers/obo_helper.py  -2
+ src/etl/allele_etl.py  -14
+ src/etl/do_etl.py  -3
+ src/etl/affected_genomic_model_etl.py  -3
+ src/etl/sequence_targeting_reagent_etl.py  -1
+ src/etl/construct_etl.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6053635&bid=19830328)

**Comment by christabone** [comment]
@sierra-moxon @ianlongden I think this is good to go -- tests are working again. Just want to double check everything is OK since it's rather large.

**Comment by ianlongden** [comment]
Absolutely, no problem, please make sure you are happy with everything, I realise it is very large. Please feel free to suggest changes I should have time to fix those.

**Pull request merged**
