### PR TITLE
Use current for GO

### PR DESCRIPTION
**Pull request by cmungall**
snapshots should not be used, cc @kltm @dustine32 

Alternatively, always use the OBO PURL

### CODE REVIEW

**Comment by oblodgett** [comment]
Can this be placed into the release-2.0.0 branch instead?

**Comment by sierra-moxon** [comment]
The current errors here, are because the most recent DO file has double quotes in the header that make the ontobio parser choke on synonyms and cross references.  We've submitted a ticket at DO and are awaiting the fix before we can go back to using the purl for DO.

**Comment by dustine32** [comment]
@cmungall Sure I can enter a ticket. I can add detail after I take a look at the updated code. The DO file double quotes are probably tricking either ontobio or owltools into ignoring synonyms and cross references.

**Comment by dustine32** [comment]
Got this issue here: https://github.com/biolink/ontobio/issues/271

**Comment by cmungall** [comment]
Ah OK, so it's a genuine syntax error, no action required then

**Comment by dustine32** [comment]
@cmungall Yep, I think once DO fixes their file it *should* work again.

**Pull request closed without merging**
