### PR TITLE
Bug fixes 3.1.0

### PR DESCRIPTION
**Pull request by sierra-moxon**
- get phenotype working for human
-

### CODE REVIEW

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 11
           

Complexity increasing per file
==============================
- src/etl/allele_etl.py  1
- src/etl/disease_etl.py  6
- src/etl/phenotype_etl.py  4
         

Clones removed
==============
+ src/etl/allele_etl.py  -7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=5566832&bid=18254906)

**Comment by adamjohnwright** [comment]
I agree with @azurbrd's comments on changing from underscore to camel case. We just changed essentially all the code to underscore. Also the logger variable has been brought inside the class everywhere and then accessed through the self variable. If you don't have a self variable you can do AlleleETL.logger.

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 11
           

Complexity increasing per file
==============================
- src/etl/allele_etl.py  1
- src/etl/transcript_etl.py  1
- src/etl/phenotype_etl.py  4
- src/etl/disease_etl.py  6
         

Clones removed
==============
+ src/etl/allele_etl.py  -7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=5566832&bid=18254906)

**Comment by sierra-moxon** [comment]
> in docker-compose.yml NEO4J_dbms_memory_pagecache__size should be NEO4J_dbms_memory_pagecache_size so that the variable is passed as dbms.memory.pagecache.size according to https://neo4j.com/docs/operations-manual/current/performance/memory-configuration/

sounds good.

> Kind of curious on why some variables changed from underscores to camelcase in src/etl/allele_etl.py. I guess we don't have a particular standard ?

yeah we don't really have a standard.

**Comment by azurebrd** [comment]
Cool cool, thanks Sierra :)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 12
           

Complexity increasing per file
==============================
- src/etl/allele_etl.py  1
- src/etl/phenotype_etl.py  4
- src/etl/transcript_etl.py  1
- src/etl/disease_etl.py  6
         

Clones removed
==============
+ src/etl/allele_etl.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=5566832&bid=18254906)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 12
           

Complexity increasing per file
==============================
- src/etl/allele_etl.py  1
- src/etl/transcript_etl.py  1
- src/etl/phenotype_etl.py  4
- src/etl/disease_etl.py  6
         

Clones removed
==============
+ src/etl/allele_etl.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=5566832&bid=18254906)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 13
           

Complexity increasing per file
==============================
- src/etl/phenotype_etl.py  8
- src/etl/disease_etl.py  6
- src/etl/allele_etl.py  1
- src/etl/transcript_etl.py  1
         

Clones removed
==============
+ src/etl/allele_etl.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=5566832&bid=18254906)

**Pull request merged**
