### PR TITLE
Feature/add expression atlas links AGR-828

### PR DESCRIPTION
**Pull request by a8wright**
I believe this is fully complete. Doug Howe said that he wants links on the UI to Expression Atlas, for genes that are in Expression Atlas, on the Alliance gene pages. Here is an example URL that he gave me: https://www.ebi.ac.uk/gxa/genes/WBGene00168555. There is a sitemap.xml file for each species in EA: https://www.ebi.ac.uk/gxa/sitemap.xml. I have created a map from data_provider to sitemap URL. I am then reading in the endpoints, parsing out the gene name from the URLs in the site map. Often they are lowercase versions of our primar_ids. For SGD I am using the secondary_id. This appears to be finding lots of matches. I am storing this URL right on the genes themselves. If you want them stored another way feel free to modify the query. 

I have not noticed any significant processing time for increases from this change. We will see based on how long it takes GOCD.

### CODE REVIEW

**Comment by a8wright** [comment]
I don't know how to get rid of the urllib Codacy error. Any ideas?

**Comment by christabone** [comment]
@a8wright Codacy compliance is optional (but encouraged), it should be OK for now.

**Comment by christabone** [comment]
@a8wright We'll need to do a bit of a re-write on this before it goes in. We typically use cross reference nodes to handle this type of implementation (I'd like to hear from @sierra-moxon too if she has a minute). The external links are stored in our Resource Descriptors file (https://github.com/alliance-genome/agr_schemas/blob/develop/resourceDescriptors.yaml) which allows us to avoid hard coding links into the loader code. Perhaps it would be best to meet and discuss this?

**Comment by a8wright** [comment]
@sierra-moxon @christabone I fully agree with leaving this to after the release. I also completed this to the point where it works but wasn't exactly in line with how things have been done so far with the rest of the schema. I had a feeling that this would need changes before it goes in. @sierra-moxon I agree that we should check with SGD about the secondary id thing. Doug Howe was fairly clear but I am not 100 percent that the logic is correct. I am almost certain that the link that are being made are correct but I am not sure if we should also be lining them up with other ids or some other additional complexity.  @christabone I am not sure when we should discuss this. There is no pressure to discuss it now. But maybe next week. I think the Loader call might be the best call for this. I think it is too early to use the architecture call. I don't want this getting in the way of work for the release.

**Comment by sierra-moxon** [comment]
I'm closing this PR for now @a8wright - lets talk about it at a loader meeting like you suggest.  That way we don't see it in the list when we're trying to get bug fix PRs out for the 2.1 release. :)

**Pull request closed without merging**
