### PR TITLE
Fix HTP samples, add protein stub, add synonyms for species

### PR DESCRIPTION
**Pull request by sierra-moxon**
AGR-2187
AGR-2414
AGR-2408
AGR-2265
AGR-2343
AGR-2415
AGR-2132

### CODE REVIEW

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 21
           

Complexity increasing per file
==============================
- src/etl/protein_sequence_etl.py  9
- src/etl/bgi_etl.py  1
- src/etl/transcript_etl.py  5
- src/etl/vep_transcript_etl.py  1
- src/etl/gene_pheno_cross_reference_etl.py  5
- src/etl/variation_etl.py  1
         

Complexity decreasing per file
==============================
+ src/etl/htp_metadatasample_etl.py  -3
+ src/etl/htp_metadataset_etl.py  -3
         

Clones added
============
- src/etl/protein_sequence_etl.py  4
- src/etl/htp_metadatasample_etl.py  2
- src/etl/gene_pheno_cross_reference_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6205572&bid=20241095)

**Review by adamjohnwright — APPROVED** [review]
That's a lot of changes!

**Review by azurebrd — APPROVED** [review]
Yeah, wow, that's a lot of work, nice !

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 21
           

Complexity increasing per file
==============================
- src/etl/gene_pheno_cross_reference_etl.py  5
- src/etl/vep_transcript_etl.py  1
- src/etl/variation_etl.py  1
- src/etl/bgi_etl.py  1
- src/etl/transcript_etl.py  5
- src/etl/protein_sequence_etl.py  10
         

Complexity decreasing per file
==============================
+ src/etl/htp_metadatasample_etl.py  -3
+ src/etl/htp_metadataset_etl.py  -3
         

Clones added
============
- src/etl/gene_pheno_cross_reference_etl.py  2
- src/etl/htp_metadatasample_etl.py  2
- src/etl/protein_sequence_etl.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6205572&bid=20241095)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 21
           

Complexity increasing per file
==============================
- src/etl/bgi_etl.py  1
- src/etl/transcript_etl.py  5
- src/etl/protein_sequence_etl.py  10
- src/etl/vep_transcript_etl.py  1
- src/etl/gene_pheno_cross_reference_etl.py  5
- src/etl/variation_etl.py  1
         

Complexity decreasing per file
==============================
+ src/etl/htp_metadataset_etl.py  -3
+ src/etl/htp_metadatasample_etl.py  -3
         

Clones added
============
- src/etl/protein_sequence_etl.py  4
- src/etl/gene_pheno_cross_reference_etl.py  2
- src/etl/htp_metadatasample_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6205572&bid=20241095)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 19
           

Complexity increasing per file
==============================
- src/etl/variation_etl.py  1
- src/etl/vep_transcript_etl.py  1
- src/etl/protein_sequence_etl.py  10
- src/etl/transcript_etl.py  5
- src/etl/gene_pheno_cross_reference_etl.py  5
- src/etl/bgi_etl.py  1
         

Complexity decreasing per file
==============================
+ src/etl/htp_metadatasample_etl.py  -3
+ src/etl/htp_metadataset_etl.py  -3
         

Clones added
============
- src/etl/htp_metadatasample_etl.py  2
- src/etl/protein_sequence_etl.py  4
- src/etl/gene_pheno_cross_reference_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6205572&bid=20241095)

**Comment by christabone** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 21
           

Complexity increasing per file
==============================
- src/etl/variation_etl.py  1
- src/etl/vep_transcript_etl.py  1
- src/etl/protein_sequence_etl.py  10
- src/etl/bgi_etl.py  1
- src/etl/gene_pheno_cross_reference_etl.py  5
- src/etl/transcript_etl.py  5
         

Complexity decreasing per file
==============================
+ src/etl/htp_metadataset_etl.py  -3
+ src/etl/htp_metadatasample_etl.py  -3
         

Clones added
============
- src/etl/htp_metadatasample_etl.py  2
- src/etl/protein_sequence_etl.py  4
- src/etl/gene_pheno_cross_reference_etl.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Alliance_of_Genome_Resources/agr_loader/pullRequest?prid=6205572&bid=20241095)

**Pull request merged**
