### PR TITLE
Submission system

### PR DESCRIPTION
**Pull request by sierra-moxon**
- initial submission system implementation
- uses 'local_submission.json' in addition to return from submission system API to get files not in the submission system.
- code to generate snapshot via the loader is there, but commented out b/c its failing on a SSL cert issue

### CODE REVIEW

**Comment by sierra-moxon** [comment]
I think gocd might've failed b/c it needs a couple of ENV variables added.

**Comment by christabone** [comment]
Good stuff, I was chatting with Olin during the meeting and there are a few small tweaks to be made to bring it in line with incoming API changes. Also a bit of old code to be removed. I'll submit a few commits tomorrow if that's OK.

**Comment by oblodgett** [comment]
@sierra-moxon `RUN apt-get install ca-certificates` is something I would rather see fixed earlier in the pipeline, because its not just going to be the loader that is effected by it.

**Comment by sierra-moxon** [comment]
> @sierra-moxon `RUN apt-get install ca-certificates` is something I would rather see fixed earlier in the pipeline, because its not just going to be the loader that is effected by it.

my preference as well.  this is me trying to do work while waiting for that to happen.

**Comment by oblodgett** [comment]
Codacy thinks this "0.0.0.0" is an IP address which it is but not in our case its a release number... this is just to strict, i'm sorry.

**Comment by sierra-moxon** [comment]
@christabone - talked to @oblodgett this morning.  how about we push this in as it is so we have something working for the release.  Then we can have a meeting about the next iteration? This is a good next step to get in as is.

**Comment by christabone** [comment]
@sierra-moxon Sounds good!

**Pull request merged**
